const defaultOverall = 1;

function computeOverallValue( playerDetails, position ) {
    const percentageValues = {
        ST: {
            finishing: 18,
            headingAcc: 10,
            shortPassing: 5,
            volleys: 2,
            dribbling: 7,
            ballControl: 10,
            acceleration: 4,
            sprintSpeed: 5,
            reactions: 8,
            shotPower: 10,
            strength: 5,
            longShots: 3,
            positioning: 13,
        },
        RW: {
            crossing: 9,
            finishing: 10,
            shortPassing: 9,
            dribbling: 16,
            ballControl: 14,
            acceleration: 7,
            sprintSpeed: 6,
            agility: 3,
            reactions: 7,
            longShots: 4,
            positioning: 9,
            vision: 6,
        },
        LW: {
            crossing: 9,
            finishing: 10,
            shortPassing: 9,
            dribbling: 16,
            ballControl: 14,
            acceleration: 7,
            sprintSpeed: 6,
            agility: 3,
            reactions: 7,
            longShots: 4,
            positioning: 9,
            vision: 6,
        },
        CF: {
            finishing: 11,
            headingAcc: 2,
            shortPassing: 9,
            dribbling: 14,
            ballControl: 15,
            acceleration: 5,
            sprintSpeed: 5,
            reactions: 9,
            shotPower: 5,
            longShots: 4,
            positioning: 13,
            vision: 8,
        },
        CAM: {
            finishing: 7,
            shortPassing: 16,
            dribbling: 13,
            longPassing: 4,
            ballControl: 15,
            acceleration: 4,
            sprintSpeed: 3,
            agility: 3,
            reactions: 7,
            longShots: 5,
            positioning: 9,
            vision: 14,
        },
        CM: {
            finishing: 2,
            shortPassing: 17,
            dribbling: 7,
            longPassing: 13,
            ballControl: 14,
            reactions: 8,
            stamina: 6,
            longShots: 4,
            interceptions: 5,
            positioning: 6,
            vision: 13,
            standingTackle: 5,
        },
        RM: {
            crossing: 10,
            finishing: 6,
            shortPassing: 11,
            dribbling: 15,
            longPassing: 5,
            ballControl: 13,
            acceleration: 7,
            sprintSpeed: 6,
            reactions: 7,
            stamina: 5,
            positioning: 8,
            vision: 7,
        },
        LM: {
            crossing: 10,
            finishing: 6,
            shortPassing: 11,
            dribbling: 15,
            longPassing: 5,
            ballControl: 13,
            acceleration: 7,
            sprintSpeed: 6,
            reactions: 7,
            stamina: 5,
            positioning: 8,
            vision: 7,
        },
        CDM: {
            shortPassing: 14,
            longPassing: 10,
            ballControl: 10,
            reactions: 7,
            stamina: 6,
            strength: 4,
            aggression: 5,
            interceptions: 14,
            vision: 4,
            marking: 9,
            standingTackle: 12,
            slidingTackle: 5,
        },
        CB: {
            headingAcc: 10,
            shortPassing: 5,
            ballControl: 4,
            sprintSpeed: 2,
            reactions: 5,
            jumping: 3,
            strength: 10,
            aggression: 7,
            interceptions: 13,
            marking: 14,
            standingTackle: 17,
            slidingTackle: 10,
        },
        RB: {
            crossing: 9,
            headingAcc: 4,
            shortPassing: 7,
            ballControl: 7,
            acceleration: 5,
            sprintSpeed: 7,
            reactions: 8,
            stamina: 8,
            interceptions: 12,
            marking: 8,
            standingTackle: 11,
            slidingTackle: 14,
        },
        LB: {
            crossing: 9,
            headingAcc: 4,
            shortPassing: 7,
            ballControl: 7,
            acceleration: 5,
            sprintSpeed: 7,
            reactions: 8,
            stamina: 8,
            interceptions: 12,
            marking: 8,
            standingTackle: 11,
            slidingTackle: 14,
        },
        RWB: {
            crossing: 12,
            shortPassing: 10,
            dribbling: 4,
            ballControl: 8,
            acceleration: 4,
            sprintSpeed: 6,
            reactions: 8,
            stamina: 10,
            interceptions: 12,
            marking: 7,
            standingTackle: 8,
            slidingTackle: 11,
        },
        LWB: {
            crossing: 12,
            shortPassing: 10,
            dribbling: 4,
            ballControl: 8,
            acceleration: 4,
            sprintSpeed: 6,
            reactions: 8,
            stamina: 10,
            interceptions: 12,
            marking: 7,
            standingTackle: 8,
            slidingTackle: 11,
        },
        GK: {
            reactions: 11,
            gkDiving: 21,
            gkHandling: 21,
            gkKicking: 5,
            gkPositioning: 21,
            gkReflexes: 21,
        },
    };

    const playerSkills = Object.keys( percentageValues[ position ] );
    let overall = 0;
    const playerPositionPercentageValues = percentageValues[ position ];
    playerSkills.forEach( ( skill ) => {
        overall += ( playerDetails[ skill ] * ( playerPositionPercentageValues[ skill ] / 100 ) );
    } );

    return Math.round( overall ) || defaultOverall;
}

export default computeOverallValue;
